version: "3.9"
services:
  backend:
    container_name: devit_group_server
    build:
      context: .
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      - MONGO_URL=${MONGO_URL}
      - UPLOAD_URL=${UPLOAD_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}

  mongo:
    image: mongo:latest
    container_name: devit_group_db
    restart: always
    volumes:
      - ./mongo/data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_URL=${MONGO_URL}